name: Deploy Front-End

on:
  push:
    paths:
      - "src/Notes.Spa/**"

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./src/Notes.Spa" # set this to the path to your web app project, defaults to the repository root

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install npm packages
        shell: bash
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          yarn install
      - name: Build app
        shell: bash
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          yarn build
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_FRONTENDAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FRONTENDAPP_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build"
